import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type {
  AdversarialReport,
  AttackCatalog,
  SecurityAttack,
  SecurityReport,
} from '@storefront/shared';

export type {
  AttackCatalog,
  AttackCatalogEntry,
  DefenceLayer,
  SecurityAttack,
  SecurityReport,
  Severity,
} from '@storefront/shared';

/**
 * Joins the adversarial suite's machine-written results to the hand-written
 * prose that explains them.
 *
 * The split is deliberate. `data/adversarial-results.json` is generated by
 * `pnpm test:adversarial` and is only ever as true as the last run — it holds
 * outcomes and evidence, nothing editorial. `data/attack-catalog.json` is
 * authored by a human and holds the sentences that go on a screen: what the
 * attack attempts, which layer stops it, and what it would have cost. Neither
 * file can be edited to change the other's meaning: prose cannot turn a failing
 * test green, and a passing test cannot invent its own severity.
 *
 * An attack present in the results but missing from the catalog is surfaced,
 * not silently dropped. A page that quietly hides a test is worse than one that
 * says it does not have the copy yet.
 */

const dataDir = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..', 'data');

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, 'utf8')) as T;
}

export function getSecurityReport(
  resultsPath = join(dataDir, 'adversarial-results.json'),
  catalogPath = join(dataDir, 'attack-catalog.json'),
): SecurityReport {
  const results = readJson<AdversarialReport>(resultsPath);
  const catalog = readJson<AttackCatalog>(catalogPath);

  const attacks: SecurityAttack[] = results.attacks.map((attack) => ({
    ...attack,
    catalog: catalog[attack.id] ?? null,
  }));

  return {
    generated_at: results.generated_at,
    total: results.total,
    held: results.held,
    broken: results.broken,
    ledger_chain: results.ledger_chain,
    attacks,
    missing_catalog_entries: attacks.filter((a) => a.catalog === null).map((a) => a.id),
  };
}
