packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true

onlyBuiltDependencies:
  - esbuild

overrides:
  db: link:../../../.local/share/pnpm/global/5/node_modules/db
  push: link:../../../.local/share/pnpm/global/5/node_modules/push
  supabase: link:../../../.local/share/pnpm/global/5/node_modules/supabase
