import type { AdversarialReport, AttackResult } from './adversarial.js';

/**
 * The attack log as the dashboard reads it: machine-written results joined to
 * hand-written prose.
 *
 * Two files, on purpose. `data/adversarial-results.json` is generated by the
 * suite and holds outcomes only. `data/attack-catalog.json` is authored by a
 * human and holds the sentences that go on a screen. Prose cannot turn a
 * failing test green, and a passing test cannot invent its own severity.
 */

/** The defence that actually stops an attack, named as an architectural layer. */
export type DefenceLayer =
  | 'quote_signature'
  | 'policy_rule'
  | 'idempotency_constraint'
  | 'ingest_sanitiser'
  | 'server_rendered_confirmation'
  | 'hash_chained_ledger';

export type Severity = 'critical' | 'high' | 'medium';

/** One hand-written entry in data/attack-catalog.json, keyed by test id. */
export interface AttackCatalogEntry {
  /** One plain sentence: what the attacker is trying to achieve. */
  attempts: string;
  layer: DefenceLayer;
  /** The policy rule_id that fires, when the layer is the policy engine. */
  rule_id?: string;
  /** How the layer stops it, in one sentence. */
  defence: string;
  /** What it would have cost had it worked. */
  severity: Severity;
}

export type AttackCatalog = Record<string, AttackCatalogEntry>;

/** An attack result with its prose attached. `catalog` is null when unwritten. */
export interface SecurityAttack extends AttackResult {
  catalog: AttackCatalogEntry | null;
}

export interface SecurityReport {
  generated_at: string;
  total: number;
  held: number;
  broken: number;
  ledger_chain: AdversarialReport['ledger_chain'];
  attacks: SecurityAttack[];
  /** Ids present in the results with no catalog entry yet. */
  missing_catalog_entries: string[];
}
